# Generated by Django 2.2.7 on 2020-01-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegister_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('proof', models.FileField(upload_to='')),
                ('cid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.Country_tb')),
                ('did', models.ForeignKey(on_delete='CASCADE', to='siteadmin.District_tb')),
                ('sid', models.ForeignKey(on_delete='CASCADE', to='siteadmin.State_tb')),
            ],
        ),
    ]
