# Generated by Django 2.2.7 on 2020-01-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_supplierregister_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierregister_tb',
            name='status',
            field=models.CharField(default='2', max_length=30),
        ),
    ]
