# Generated by Django 2.2.7 on 2020-01-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_supplierregister_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_tb',
            name='sid',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.State_tb'),
        ),
        migrations.AddField(
            model_name='state_tb',
            name='cid',
            field=models.ForeignKey(default='1', on_delete='CASCADE', to='siteadmin.Country_tb'),
        ),
    ]
