# Generated by Django 2.2.7 on 2020-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_auto_20200114_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierregister_tb',
            name='Contactnumber',
            field=models.CharField(default='2', max_length=30),
        ),
    ]
