# Generated by Django 2.2.7 on 2020-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_order_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
