# Generated by Django 2.2.7 on 2020-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_order_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
